### PR TITLE
Feature/2789 new rules and deps

### LINKED ISSUE #50: Need to support latest versions of eslint packages
#### Describe the desired behavior
We should be supporting the latest versions of the eslint plugin, parser, etc.

#### Describe the current behavior
We are a major version (or two) behind the latest for some packages.

#### Is this request related to a current issue?
This is related to new React projects failing to run out of the box when created with the BLUI CLI.

#### Additional Context

We might be able to get away with using >= as the dependency condition, but if we want to be more cautious we can use the caret syntax to lock down to the current latest major version.

### PR DESCRIPTION
**Pull request by emclaug2**
Fixes #50  #33 

#### Changes proposed in this Pull Request:
- Updated all deps to latest, still testing locally. 
- Adjusted rule for shadow-vars.

### CODE REVIEW

**Comment by emclaug2** [comment]
Instead of making this a major breaking change, I'm thinking we can start to introduce dependency ranges.   Still thinking this over.

**Comment by emclaug2** [comment]
Looking more closely at this, updating eslint to the v8.0.0 will introduce an incompatible peer dependency warning, so I'm thinking we can make this a major version change:

Dependencies & their Peer Dependencies
      
**AFTER**
        "eslint-plugin-react": "^7.28.0",                      "eslint": "^3 || ^4 || ^5 || ^6 || ^7 || ^8"
        "eslint-config-prettier": ">= 8.0.0"                   "eslint": ">=7.0.0"
        "@typescript-eslint/parser": "^5.9.0",                 "eslint": "^6.0.0 || ^7.0.0 || ^8.0.0"
        "@typescript-eslint/eslint-plugin": "^5.9.0",          "@typescript-eslint/parser": "^5.0.0", "eslint": "^6.0.0 || ^7.0.0 || ^8.0.0"
        "eslint": ">= 8.6.0",


**BEFORE**
	"eslint-plugin-react": "^7.16.0"        
        "eslint-config-prettier": ">= 6.3.0"                
        "@typescript-eslint/parser": "^4.8.0",
        "@typescript-eslint/eslint-plugin": "^4.8.0",
        "eslint": ">= 5.0.0",

**Review by huayunh — APPROVED** [review]
Can verify this works when I mess around with docit.

**Comment by jeffvg** [comment]
with these upgrades, (react) should we do anything about typescript-eslint warnings we see or is this out of scope for this particular effort?

image

**Comment by emclaug2** [comment]
> with these upgrades, (react) should we do anything about typescript-eslint warnings we see or is this out of scope for this particular effort?
> 
> image

I'll take a look and see if we can get away with using v4.5.0 for TS; I'll merge this in so we can work with a beta package but I'll be doing some more testing using our cli-generated projects.

**Comment by emclaug2** [comment]
> I'll take a look and see if we can get away with using v4.5.0 for TS; I'll merge this in so we can work with a beta package but I'll be doing some more testing using our cli-generated projects.

This warning goes away when using BLUI CLI & latest deps required in the beta package.

**Pull request merged**
